/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.CommunicationController;
import domain.Stado;
import domain.Zivotinja;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;

/**
 *
 * @author anakl
 */
public class FrmStado extends javax.swing.JFrame {

    private TableModelKlijent tmk;
    private JTextField text;

    /**
     * Creates new form FrmStado
     */
    public FrmStado(TableModelKlijent tmk, JTextField text) {
        initComponents();
        setLocationRelativeTo(null);
        this.tmk = tmk;
        this.text = text;
        prepareView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbZivotinja = new javax.swing.JComboBox<>();
        txtBrojGrla = new javax.swing.JTextField();
        btnDodaj = new javax.swing.JButton();
        btnZavrsi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Zivotinja:");

        jLabel2.setText("Broj grla:");

        btnDodaj.setText("Dodaj stado");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        btnZavrsi.setText("Zavrsi");
        btnZavrsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZavrsiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBrojGrla)
                            .addComponent(cmbZivotinja, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 198, Short.MAX_VALUE)
                        .addComponent(btnDodaj)
                        .addGap(30, 30, 30)
                        .addComponent(btnZavrsi)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbZivotinja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtBrojGrla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDodaj)
                    .addComponent(btnZavrsi))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed
        try {
            Zivotinja z = (Zivotinja) cmbZivotinja.getSelectedItem();
            Stado s = new Stado();
            s.setZivotinja(z);
            Long brojGrla = Long.valueOf(txtBrojGrla.getText());
            s.setBrojGrla(brojGrla);
            BigDecimal subvencijaPoGrlu = z.getSubvencijaPoGrlu();
            BigDecimal iznosSubvencije = subvencijaPoGrlu.multiply(BigDecimal.valueOf(brojGrla));
            s.setIznosSubvencije(iznosSubvencije);
            System.out.println("Broj grla: " + brojGrla);
            System.out.println("Subvencija po grlu: " + subvencijaPoGrlu);
            System.out.println("Iznos subvencije: " + iznosSubvencije);
            CommunicationController.getInstance().dodajStado(s);
            List<Stado> stada = CommunicationController.getInstance().vratiStadaIzMemorije();
            tmk.azuriraj(stada);
            BigDecimal subv = tmk.vratiUkupnoSubvencija();
            text.setText(subv + "");
            dispose();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnDodajActionPerformed

    private void btnZavrsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZavrsiActionPerformed
        dispose();
    }//GEN-LAST:event_btnZavrsiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnZavrsi;
    private javax.swing.JComboBox<Object> cmbZivotinja;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtBrojGrla;
    // End of variables declaration//GEN-END:variables

    private void prepareView() {
        try {
            List<Zivotinja> zivotinje = CommunicationController.getInstance().getAllZivotinje();
            for (Zivotinja zivotinja : zivotinje) {
                cmbZivotinja.addItem(zivotinja);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
}
